# Starter pipeline



trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- script: |
    python -m pip install flake8
    flake8 . || true
  displayName: 'Run lint tests'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure for Students(8509b3d0-71a6-4205-ad8e-bb992cac7468)'
    azureContainerRegistry: '{"loginServer":"yyyyyy.azurecr.io", "id" : "/subscriptions/8509b3d0-71a6-4205-ad8e-bb992cac7468/resourceGroups/DefaultResourceGroup-DEWC/providers/Microsoft.ContainerRegistry/registries/yyyyyy"}'
    dockerComposeFile: '**/Dockerfile'
    projectName: 'Task4'
    action: 'Run a Docker Compose command'